@echo off
echo Initializing Git...
git init
echo Adding files...
git add .
echo Committing changes...
git commit -m "Finalizing dashboard fixes, notification redirection, and UI enhancements"
echo Adding remote...
git remote add origin https://github.com/pancham-sharma/6year-project.git
echo Pushing to GitHub...
git push -u origin main
if %errorlevel% neq 0 (
    echo Pushing to master instead...
    git push -u origin master
)
echo.
echo Done! If you see errors, make sure you are logged into GitHub CLI or have your credentials ready.
pause
