# Generated by Django 6.0.4 on 2026-05-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Recycled', 'Recycled')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Recycled', 'Recycled')], default='Active', max_length=20),
        ),
    ]
