# Generated by Django 6.0.4 on 2026-05-10 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_is_edited_message_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='read',
            new_name='is_read',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_body',
            new_name='message',
        ),
    ]
