# Generated by Django 5.2.13 on 2026-04-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupdetails',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pickupdetails',
            name='full_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pickupdetails',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='pickupdetails',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
