# Generated by Django 5.2.13 on 2026-04-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_pickupdetails_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
