# Generated by Django 6.0.4 on 2026-05-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donation_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('impact_badge', models.CharField(blank=True, help_text='e.g. ₹500 feeds 5 people', max_length=100)),
                ('icon_name', models.CharField(default='Heart', help_text='Lucide icon name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
