# Generated by Django 6.0.4 on 2026-05-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupdetails',
            name='assigned_team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
