# Generated by Django 6.0.4 on 2026-05-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_pickupdetails_assigned_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='backups/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('backup_type', models.CharField(default='json', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='donation',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Recycled', 'Recycled')], default='Pending', max_length=20),
        ),
    ]
