# Generated by Django 6.0.4 on 2026-05-09 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_databasebackup_alter_donation_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='unit_name',
            field=models.CharField(default='Units', help_text='e.g. Meals, Clothes, Trees', max_length=50),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['timestamp'], name='donations_d_timesta_a03a92_idx'),
        ),
    ]
