# Generated by Django 6.0.4 on 2026-05-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_category_unit_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='unit',
            field=models.CharField(blank=True, default='Units', max_length=20, null=True),
        ),
    ]
