# Generated by Django 6.0.4 on 2026-05-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_donation_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='donation',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
