# Generated by Django 6.0.4 on 2026-05-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_alter_donation_options_alter_donation_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='impact_label',
            field=models.CharField(blank=True, help_text='e.g. Families Helped, People Fed', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='impact_per_quantity',
            field=models.IntegerField(default=1, help_text='Quantity needed to achieve 1 impact unit'),
        ),
    ]
