# Generated by Django 6.0.4 on 2026-05-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_category_impact_label_category_impact_per_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Recycled', 'Recycled')], db_index=True, default='Pending', max_length=20),
        ),
    ]
