# Generated by Django 5.2.13 on 2026-04-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='distributed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
