# Generated by Django 6.0.4 on 2026-05-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_distributed'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_name',
            field=models.CharField(default='Units', max_length=50),
        ),
    ]
