# Generated by Django 6.0.4 on 2026-05-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_firebase_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='user',
        ),
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_secret',
        ),
        migrations.RemoveField(
            model_name='user',
            name='two_factor_enabled',
        ),
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
