# Generated by Django 6.0.4 on 2026-05-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_emailotp_user_delete_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteerapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='status',
            field=models.CharField(db_index=True, default='Pending', max_length=20),
        ),
    ]
